on:
  push:
    branches: [ "main" ]
    path-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    path-ignore:
      - '**.md'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install conda dependencies
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '2.0.5-0'
        environment-file: environment-test.yml
        init-shell: bash
        cache-environment: true
        post-cleanup: 'environment'

    - name: Install pip dependencies
      run: pip install .[dev]
      shell: bash -el {0}

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.1'
        use-public-rspm: true

    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: true

    - name: Lint with flake8
      run: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash -el {0}
      
    - name: Just see where we are
      run: ls
      shell: bash -el {0}

    - name: Test with pytest
      run: pytest --cov --log-cli-level INFO --clear_inputs --cov-report json
      shell: bash -el {0}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
